# Site settings
title: FOSS events
email: estetus@gmail.com
description: A simple list of FOSS conferences and workshops, published collaboratively with community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fossconferences.github.io/" # the base hostname & protocol for your site
twitter_username: estet
github_username: ligurio

# Build settings
markdown: kramdown
